# Generated by Django 4.2.3 on 2023-09-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=45, verbose_name='Name')),
                ('article_price', models.IntegerField(verbose_name='Price')),
                ('article_section', models.CharField(max_length=50, verbose_name='Section')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=25, verbose_name='Name')),
                ('customer_lastname', models.CharField(max_length=25, verbose_name='Lastname')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('customer_phone_num', models.CharField(max_length=35, verbose_name='Phone Number')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_num', models.IntegerField(verbose_name='Order Number')),
                ('Order_date', models.DateField()),
            ],
        ),
    ]
