# Generated by Django 4.2.3 on 2023-09-22 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Order_date',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Order_num',
            new_name='order_num',
        ),
    ]
