# Generated by Django 4.2.3 on 2023-10-31 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_rename_order_date_orders_order_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
