# Generated by Django 4.2.3 on 2023-09-30 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=25, verbose_name='Category Name')),
                ('category_creation', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('category_date_update', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='Title')),
                ('content', models.CharField(max_length=600, verbose_name='Content')),
                ('img', models.ImageField(upload_to='', verbose_name='Image')),
                ('post_creation', models.DateTimeField(auto_now_add=True, verbose_name='Post Creation')),
                ('post_update', models.DateTimeField(auto_now=True, verbose_name='Post Update')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(to='blog.category')),
            ],
        ),
    ]
