# Generated by Django 4.2.3 on 2023-09-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_services_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
