# Generated by Django 4.2.3 on 2023-09-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_services_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='services',
            name='datetime',
            field=models.DateTimeField(verbose_name='Update Date'),
        ),
    ]
