# Generated by Django 4.2.3 on 2023-09-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_services_created_alter_services_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Date'),
        ),
    ]
