# Generated by Django 4.2.3 on 2023-10-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_services_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='img',
            field=models.ImageField(upload_to='services'),
        ),
    ]
