# Generated by Django 4.2.3 on 2023-10-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=75, verbose_name='Name')),
                ('category_creation', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('category_update', models.DateTimeField(auto_now=True, verbose_name='Update date')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_title', models.CharField(max_length=50, verbose_name='Image Title')),
                ('img', models.ImageField(upload_to='shop', verbose_name='Image')),
                ('img_date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('img_date_update', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('product_description', models.CharField(max_length=500, verbose_name='Description')),
                ('product_post_creation', models.DateTimeField(auto_now_add=True, verbose_name='Post Created')),
                ('product_post_update', models.DateTimeField(auto_now=True, verbose_name='Post Update')),
                ('product_category', models.ManyToManyField(to='shop.category', verbose_name='Product Category')),
            ],
            options={
                'verbose_name': 'Product Detail',
                'verbose_name_plural': 'Products Details',
            },
        ),
    ]
