# Generated by Django 4.2.3 on 2023-10-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='shop', verbose_name='Product Image'),
        ),
    ]
