# Generated by Django 4.2.3 on 2023-10-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_details_product_stockist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_details',
            old_name='product_description',
            new_name='product_details',
        ),
    ]
