# Generated by Django 4.2.3 on 2023-10-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_product_description_product_details_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='product_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Product Price'),
        ),
    ]
