# Generated by Django 4.2.3 on 2023-10-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_details_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='product_category',
            field=models.ManyToManyField(to='shop.category'),
        ),
    ]
