# Generated by Django 4.2.3 on 2023-10-22 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_details_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='product_disponibilidad',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='product_details',
            name='product_category',
        ),
        migrations.AddField(
            model_name='product_details',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
    ]
